# Chapter 12: Custom Models and Training with TensorFlow

In [1]:
# Preliminaries
import sklearn
import tensorflow as tf
from tensorflow import keras
import numpy as np
import os

# Random seeds
np.random.seed(42)
tf.random.set_seed(42)

# Plots
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

## 1. Overview of TensorFlow

__Summary__ :
  - Core is similar to numpy, but with GPU support
  - Supports distributed computing
  - JIT (just-in-time) compiler; extracts _computation graph_ from Python function and optimizes + runs
  - Can export computation graph
  - Autodiff, optimizer implementation
  - Each tf op implemented in C++ (can write own ops in C++ API)
  
__Other notable features__ :
  - `tf.keras`
  - Data loading and preprocessing: `tf.data`, `tf.io`, ...
  - Image processing: `tf.image`
  - Signal processing: `tf.signal`

### 1.1 Tensors and Operations

#### 1.1.1 Basics

Can create tensor with `tf.constant()`

In [3]:
# Example: tensor matrix with two rows, three cols of floats

tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]) # matrix!

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
# Scalar
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

Each `tf.Tensor` has shape and data type (`dtype`)

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6,]])
t.shape

TensorShape([2, 3])

In [6]:
t.dtype

tf.float32

Similar indexing to numpy

In [7]:
t[:, 1:] # every row, col 2+

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [8]:
t[..., 1, tf.newaxis] # every row, only column 1

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

#### 1.1.2 Tensor operations

In [9]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [10]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [11]:
t @ tf.transpose(t) # matrix multiply

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>